stages:
- image

php_image:
  stage: image
  image: docker:latest
  services:
  - docker:dind
  script: |
    mkdir -p ~/.docker && echo "$DOCKER_AUTH_CONFIG" >~/.docker/config.json
    export version=`expr ${CI_COMMIT_TAG} ':' '\([^-]\+\)'`
    export major_version=`expr ${version} ':' '\([^.]\+\)'`
    export minor_version=`expr ${version} ':' '[^.]\+\.\([^-]\+\)'`
    export suffix=`expr ${CI_COMMIT_TAG} ':' '[^-]\+-\(.*\)'`
    docker build -t ubleipzig/vufind-php:${version}-${suffix} -f ${version}/Dockerfile .
    docker push ubleipzig/vufind-php:${version}-${suffix}
    for tag in "latest" "{major_version}" "${version}"; do
      if [ "$tag" == "latest" -a "${version}" != "7.2" ]; then continue; fi
      docker tag ubleipzig/vufind-php:${version}-${suffix} ubleipzig/vufind-php:${tag}
      docker push ubleipzig/vufind-php:${tag}
    done
    docker build -t ubleipzig/vufind-php:${version}-${suffix}-debug -f ${version}/debug/Dockerfile .
    docker push ubleipzig/vufind-php:${version}-${suffix}-debug
    for tag in "latest-debug" "{major_version}-debug" "${version}-debug"; do
      if [ "$tag" == "latest-debug" -a "${version}" != "7.2" ]; then continue; fi
      docker tag ubleipzig/vufind-php:${version}-${suffix}-debug ubleipzig/vufind-php:${tag}
      docker push ubleipzig/vufind-php:${tag}
    done
  tags:
  - docker
  only:
  - /^[57]\.\d+/
  except:
  - branches

php_vufind1_image:
  stage: image
  image: docker:latest
  services:
  - docker:dind
  script: |
    mkdir -p ~/.docker && echo "$DOCKER_AUTH_CONFIG" >~/.docker/config.json
    export version=`expr ${CI_COMMIT_TAG} ':' 'vufind1/\([^-]\+\)'`
    export major_version=`expr ${version} ':' '\([^.]\+\)'`
    export minor_version=`expr ${version} ':' '[^.]\+\.\([^-]\+\)'`
    export suffix=`expr ${CI_COMMIT_TAG} ':' 'vufind1/[^-]\+-\(.*\)'`
    docker build -t ubleipzig/vufind-php:${version}-${suffix}-vufind1-debug -f ${version}/vufind1/debug/Dockerfile .
    docker push ubleipzig/vufind-php:${version}-${suffix}-vufind1-debug
    for tag in "{major_version}-vufind1-debug" "${version}-vufind1-debug" "vufind1-debug"; do
      docker tag ubleipzig/vufind-php:${version}-${suffix}-vufind1-debug ubleipzig/vufind-php:${tag}
      docker push ubleipzig/vufind-php:${tag}
    done
  tags:
  - docker
  only:
  - /^vufind1-/
  except:
  - branches